.qp.go[500;500]
    .qp.theme[`aspect_ratio`legend_use!(`square; 0b)]   
        .qp.theme[.gg.dash.dark]
             .qp.path[-500 sublist select from devTable where time > 18803D04:07:45.599174900, myID like "1*" ; `posX; `posY]
                  .qp.s.aes[`alpha; `time]
                 , .qp.s.scale[`alpha; .gg.scale.alpha[0;255]]
                 , .qp.s.aes[`size; `time]
                 , .qp.s.scale[`size; .gg.scale.line.size[0; 5]]  
                 , .qp.s.aes[`fill; `myID]
                 , .qp.s.geom[``group!(::;`myID)]